--- #YAML:1.0
name:                Path-Ancestor
version:             0.01
abstract:            Find the longest common ancestor of N paths
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    List::Util:                    1.18
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
